### ISSUE TITLE
NullPointerException in CodeInspect

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#103]
I just got a NullPointerException in CodeInspect, see attached image. This seems to happen when the debug connection to the phone is a bit unstable.
![npe codeinspect](https://cloud.githubusercontent.com/assets/2691304/6844620/f50f5882-d3ac-11e4-8d75-1d856122a792.png)

**Comment by MarcMil** [comment]
Fixed.
