### ISSUE TITLE
Numerous errors for an apk

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/CodeInspect#105]
CodeInspect produces numerous errors for attached apk, and cannot produce output.apk.

![image](https://cloud.githubusercontent.com/assets/2270027/6865394/47be45c4-d4a8-11e4-8982-81223166d78b.png)

sample: https://onedrive.live.com/redir?resid=A81B51F05D7E3C2F%2133680

**Comment by MarcMil** [comment]
This bug is hopefully fixed now. I have started a new nightly build, it will take about half an hour. Could you retry it the new nightly built then?

Thank you very much

**Comment by flankerhqd** [comment]
Seemed fixed in new nightly build. Nice work :+1:
