### ISSUE TITLE
Cannot produce output.apk for the test apk, however no errors shown

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/CodeInspect#112]
Test apk: https://onedrive.live.com/redir?resid=A81B51F05D7E3C2F!52483&authkey=!AOSIHbOBgOSaFTE&ithint=file%2capk

**Comment by MarcMil** [comment]
I tried it with the newest nightly build. It works for me, but it takes a long time, since the app is really huge.

**Comment by flankerhqd** [comment]
Seems worked now with newest nightly build.
