### ISSUE TITLE
Add "permission use" view

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#115]
There should be a view that lists all permission used in the application as root nodes of a tree. The next level should contain the classes in which the uses happen in the code. On the third level, the concrete methods should be listed. Double-clicking on a class or a method should open the respective code in the Jimple editor. As a source for the mapping between permissions and API method, the PScout list can be used.

**Comment by MarcMil** [comment]
Implemented. However, we should think about an appropriate icon for "permission".
