### ISSUE TITLE
Possible to debug apk without repackaging it?

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/CodeInspect#126]
Currently codeinspect need to repackage and resign the apk, which will break some targets' self sign-check. Anyway to debug an existing apk on a debuggable-set phone, without repackaging the target?

As the phone is set with debuggable (ro.debuggable=1, ro.secure=0) there is no need to set  debuggable=true in AndroidManifest.

**Comment by MarcMil** [comment]
The problem is, that there is no line number information in the original apk, thus debugging wouldn't be much fun. Therefore, this is sadly currently out of scope.

**Comment by flankerhqd** [comment]
Thanks MarcMil for your explaintation. So if I understand and observed correctly, codeinspect's repacking maps jimple line number onto corresponding dalvik instruction?

**Comment by MarcMil** [comment]
Yes, that's true.
