### ISSUE TITLE
CodeInspect internal update mechanism is not working!

### ISSUE THREAD

**Issue by srasthofer** [secure-software-engineering/CodeInspect#130]
Just tried to use the Help -> Check for updates feature in CodeInspect (Eclipse). It is not working on my Mac. Anyone with similar issues?

**Comment by StevenArzt** [comment]
What do you mean by "not working"? Please be more precise. On Windows, all seems to work fine.

**Comment by srasthofer** [comment]
Not working means not working... There is no error, it says there are no updates available, but there is an update!!!

**Comment by StevenArzt** [comment]
Most likely, this was not marked as an update. We have the problem that Eclipse checks for updates using version numbers. If we mark every new nightly build with a new version number, you would get an update every day even if nothing changed. If we never change the version number, you will never get an update. At the moment, only some builds manually get a higher version number. For those updates, the automatic update version works totally fine.

@MarcMil When do you increase the version number at the moment? Maybe this was not done for a while.

**Comment by MarcMil** [comment]
Steven is right. I have now manually increased the version number and eclipses update mechanism works thus fine for me. We should consider creating a policy on when to increment the version number.
