### ISSUE TITLE
Renaming?

### ISSUE THREAD

**Issue by phros** [secure-software-engineering/CodeInspect#131]
Hi,

how is the current status from the whole rename-stuff? I just downloaded the nightly build and tried to rename different things with following results:
Renaming a package: 
* nothing happens

Renaming a class: 
* telling me "Problems encountered while moving resources. This file system is read only: packagefs://669584623.apk/com.security.certificate.b.
* after this, the file has been renamend but has no content anymore

Renaming method (at declaration):
* Rename dialog shows up
* after pressing ok, the name stays the same

Renaming Method (within a function body)
* 1st try: Error initializing Refactoring: java.io.FileNotFoundException:  (Datei oder Verzeichnis nicht gefunden)
* 2nd try: nothing happens

Is it just me, am I missing something?

**Comment by srasthofer** [comment]
Could you provide the apk? - Is it the Pincer malware (SHA256: ccad414278de526be50bbd05578c88eb56ce845e44a75ad0a9d2f0b0c4f163ca)?

**Comment by phros** [comment]
Yes indeed, it is the Pincer malware with your SHA256 hash.

**Comment by srasthofer** [comment]
Ok. We will have a look into it. Thx

**Comment by StevenArzt** [comment]
@MarcMil Do we have any updates on this issue?

**Comment by MarcMil** [comment]
In the newest version, we now support each of the renaming operations mentioned in the original issue description as well as drag & drop between packages.
Thus, I close this bug now - if there is still a renaming bug, this bug can be either reopened or a new bug can be filed.
