### ISSUE TITLE
Adding new jimple-files

### ISSUE THREAD

**Issue by srasthofer** [secure-software-engineering/CodeInspect#133]
I was trying to add a new jimple file in CodeInspect with right-click on package name NEW -> FILE. I am not able to create a new file. Get the following exception:
![bildschirmfoto 2015-05-29 um 17 39 29](https://cloud.githubusercontent.com/assets/3647928/7886375/f3b8fc72-0629-11e5-85d3-433130d51f03.png)

**Comment by StevenArzt** [comment]
This issue still exists with the current nightly build.

**Comment by MarcMil** [comment]
Fixed
