### ISSUE TITLE
looks like adb discconects on a windows machine

### ISSUE THREAD

**Issue by srasthofer** [secure-software-engineering/CodeInspect#139]
Setup: Windows is running in a VM + Emulator is Genymotion
Error-Message:
![screen shot 2015-07-03 at 15 14 29 2](https://cloud.githubusercontent.com/assets/3647928/8500080/2e01a804-2199-11e5-85d2-5269e0d74792.png)

**Comment by srasthofer** [comment]
just verified, CodeInspect is able to debug the app on my Mac + x86 emulator. So it is not directly a CodeInspect issue, but we have a look into it

**Comment by MarcMil** [comment]
Is this still reproducable with the current version?
