### ISSUE TITLE
Endless loop outputing GC messages running output.apk

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/CodeInspect#141]
The apk is repackaged successfully, however running it produces endless

 "D/dalvikvm(16744): GC_CONCURRENT freed 512K, 6% free 11118K/11719K, paused 3ms+2ms, total 20ms
D/dalvikvm(16744): WAIT_FOR_CONCURRENT_GC blocked 11ms
D/dalvikvm(16744): GC_CONCURRENT freed 511K, 6% free 11118K/11719K, paused 2ms+1ms, total 21ms
D/dalvikvm(16744): WAIT_FOR_CONCURRENT_GC blocked 13ms
D/dalvikvm(16744): GC_CONCURRENT freed 512K, 6% free 11118K/11719K, paused 1ms+2ms, total 14ms
D/dalvikvm(16744): WAIT_FOR_CONCURRENT_GC blocked 8ms
D/dalvikvm(16744): GC_CONCURRENT freed 511K, 6% free 11118K/11719K, paused 1ms+3ms, total 18ms
D/dalvikvm(16744): WAIT_FOR_CONCURRENT_GC blocked 11ms
D/dalvikvm(16744): GC_CONCURRENT freed 489K, 6% free 11118K/11719K, paused 12ms+2ms, total 27ms
D/dalvikvm(16744): GC_CONCURRENT freed 394K, 6% free 11118K/11719K, paused 11ms+11ms, total 34ms
D/dalvikvm(  522): WAIT_FOR_CONCURRENT_GC blocked 0ms
D/dalvikvm(16744): GC_CONCURRENT freed 512K, 6% free 11118K/11719K, paused 12ms+3ms, total 27ms
D/dalvikvm(16744): WAIT_FOR_CONCURRENT_GC blocked 10ms
D/dalvikvm(  522): GC_EXPLICIT freed 1550K, 37% free 16797K/26631K, paused 2ms+9ms, total 55ms
D/dalvikvm(16744): GC_CONCURRENT freed 512K, 6% free 11118K/11719K, paused 12ms+6ms, total 33ms
D/dalvikvm(16744): WAIT_FOR_CONCURRENT_GC blocked 17ms
D/dalvikvm(16744): GC_CONCURRENT freed 427K, 5% free 11241K/11719K, paused 12ms+16ms, total 51ms
D/dalvikvm(16744): GC_CONCURRENT freed 668K, 7% free 11118K/11847K, paused 12ms+2ms, total 31ms
D/dalvikvm(16744): WAIT_FOR_CONCURRENT_GC blocked 12ms
D/dalvikvm(16744): GC_CONCURRENT freed 512K, 7% free 11118K/11847K, paused 3ms+2ms, total 21ms
D/dalvikvm(16744): WAIT_FOR_CONCURRENT_GC blocked 14ms
D/dalvikvm(16744): GC_CONCURRENT freed 512K, 7% free 11118K/11847K, paused 2ms+2ms, total 21ms
D/dalvikvm(16744): WAIT_FOR_CONCURRENT_GC blocked 15ms
D/dalvikvm(16744): GC_CONCURRENT freed 511K, 7% free 11118K/11847K, paused 2ms+2ms, total 19ms
D/dalvikvm(16744): WAIT_FOR_CONCURRENT_GC blocked 12ms" messages, and eventually ANR.

Test apk: https://onedrive.live.com/redir?resid=A81B51F05D7E3C2F!61209&authkey=!AN8yNF6chuXvG2o&ithint=file%2capk

**Comment by MarcMil** [comment]
It seems to be a soot problem.
Steven, can you say something about this?
The jimple code:
```
      $MemoryCacheAware = staticinvoke <com.nostra13.universalimageloader.core.DefaultConfigurationFactory: com.nostra13.universalimageloader.cache.memory.MemoryCacheAware createMemoryCache(int)>($int_1);
      this.<com.nostra13.universalimageloader.core.ImageLoaderConfiguration$Builder: com.nostra13.universalimageloader.cache.memory.MemoryCacheAware memoryCache> = $MemoryCacheAware;

  label4:
      $z0 = this.<com.nostra13.universalimageloader.core.ImageLoaderConfiguration$Builder: boolean denyCacheImageMultipleSizesInMemory>;
```
The baksmali code of Output.apk:
```
    .line 329
    :goto_29
    move-object/from16 v0, p0

    ...
    .line 357
    invoke-static {v13}, Lcom/nostra13/universalimageloader/core/DefaultConfigurationFactory;->createMemoryCache(I)Lcom/nostra13/universalimageloader/cache/memory/MemoryCacheAware;

    move-result-object v10

    .line 358
    :goto_7d
    move-object/from16 v0, p0

    goto :goto_7d // this should go to the statement in the .line 358

    :goto_80
    goto/32 :goto_29

    .line 358
    iput-object v10, v0, Lcom/nostra13/universalimageloader/core/ImageLoaderConfiguration$Builder;->memoryCache:Lcom/nostra13/universalimageloader/cache/memory/MemoryCacheAware;
```

Seems to be a bug in the long jump splitter?
The goto does not skip the inserted goto-jump.

**Comment by StevenArzt** [comment]
I have fixed the bug in Soot and triggered a new CodeInspect build. The GOTO instructions now look correct to me in the new Soot version.

@MarcMil  Can you please confirm that the issue has been resolved?

**Comment by MarcMil** [comment]
Yes, the issue does not occur any more. Thank you, Steven!
