### ISSUE TITLE
XML layout issues

### ISSUE THREAD

**Issue by srasthofer** [secure-software-engineering/CodeInspect#142]
It seems that apktool has another issue with xml files... I opened an issue at their issue tracker:
https://github.com/iBotPeaches/Apktool/issues/988

app:
https://dl.dropboxusercontent.com/u/18007092/SENDSECRET.apk

problems:
-error: Error parsing XML: not well-formed (invalid token)
-missing ">" or "/>"

**Comment by MarcMil** [comment]
That's not an apktool bug. It is a "bug" in aapt; see also here:
https://groups.google.com/forum/#!topic/adt-dev/CER-RNfiYjo
For now, it seems that a new patch for aapt is required so that is forced to read the file as UTF-8.

**Comment by MarcMil** [comment]
Fixed for all platforms
