### ISSUE TITLE
Obfuscated Class Names - Manifest issue

### ISSUE THREAD

**Issue by srasthofer** [secure-software-engineering/CodeInspect#143]
The following app has some name obfuscation (problably dexguard or proguard):
https://dl.dropboxusercontent.com/u/18007092/SENDSECRET.apk

The app was also referred in #142. 
The AndroidManifest.xml includes the following line:
```xml
 <activity android:label="@string/title_activity_send_secret" android:name="o.ﮂ" />
```
Unfortunately, there is no class o.ﮂ in the apk. There are only #u.... files and CodeInspect (or apktool) converts the #u... into a proper unicode which is not correct here. Please double-check!

**Comment by MarcMil** [comment]
Fixed for all platforms
