### ISSUE TITLE
Import APK from phone as Jimple: missing information

### ISSUE THREAD

**Issue by ilmoka** [secure-software-engineering/CodeInspect#156]
When importing a new project using the 
import APK from phone" functionality, after selecting my device (samsung GT-I9515, API version 21) i get the list of all the apps installed.
The columns Version Name, Path to APK, First install time, Update time and Target SDK are initially empty and it takes some seconds to fill the content.

![screenshot from 2015-08-28 15 27 46](https://cloud.githubusercontent.com/assets/531867/9547261/60daa600-4d99-11e5-8f32-1b632d076b97.png)

If I select an app during this time (i.e. while the 5 columns are still empty), I can proceed with the import and everything goes fine.

![screenshot from 2015-08-28 15 28 24](https://cloud.githubusercontent.com/assets/531867/9547268/7091e248-4d99-11e5-8899-605b4cdef3b7.png)

If, instead, I wait until the rest of the metadata is loaded, 

![screenshot from 2015-08-28 15 28 54](https://cloud.githubusercontent.com/assets/531867/9547284/84210f28-4d99-11e5-9682-332bb392130a.png)

then no matter what app I choose, I always get the following error:

![screenshot from 2015-08-28 15 26 24](https://cloud.githubusercontent.com/assets/531867/9547247/42962142-4d99-11e5-9e6f-effb5c707f4a.png)

**Comment by MarcMil** [comment]
This bug should be fixed, please try again using the new nightly build.

**Comment by StevenArzt** [comment]
The current nightly build still has a similar problem. If I try to import an app from a Nexus 5 phone running API 22, I can only continue in the import wizard if I select the app before the detail data has been loaded. If I wait until all data has been loaded, I get a "Permission denied" error. If I'm quick enough, the import works all fine.

**Comment by MarcMil** [comment]
Permission denied? That's interesting. I guess we will have to test this on a real device then the next time  I am at SIT.

**Comment by MarcMil** [comment]
No longer reproducable, also with the newest version of CodeInspect and the respective phone.
