### ISSUE TITLE
Feature request: filter for app list on phone

### ISSUE THREAD

**Issue by ilmoka** [secure-software-engineering/CodeInspect#157]
The possibility of importing apks directly from the phone is very nice.
On a normal phone, though, this list can be pretty long.

In the current version of the tool, the list is sorted by package name, which makes it hard to find a specific app if one doesn't know the name of the package.

It would be cool if it was possible to 

a) add a column with the name of the application and/or
b) filter the table based on a regex, or a simple search box

-E-

**Comment by MarcMil** [comment]
b is now implemented.
Regarding a: Reading the application label in a fast and portable manner does not seem feasible at this moment: https://android.stackexchange.com/questions/90141/obtain-package-name-and-common-name-of-apps-via-adb
