### ISSUE TITLE
Error: missing metadata tag

### ISSUE THREAD

**Issue by ilmoka** [secure-software-engineering/CodeInspect#159]
After installing a certain application from the Play Store, I tried to import it from the device (succeded) and then run it on the device without any modification.
The app starts, but then crashes at the first screen, with the useless apology message of my android.
I then checked with logcat and the error seems to be some missing metadata

`C:\>adb shell "logcat | grep -i <name of the app> | grep "E/"`

`E/ValidateServiceOp( 1592): Missing metadata tag with the name  com.google.android.gms.appstate.APP_ID" in the application tag of the manifest for  com.name.of.the.app`

`E/ValidateServiceOp( 1592): Using Google Play games services requires a metadata tag with the name "com.google.android.gms.games.APP_ID" in the application tag of the manifest for com.name.of.the.app`

That is curious, because this info is present in the manifest file

![capture](https://cloud.githubusercontent.com/assets/531867/9636950/76e3b118-519e-11e5-9fd2-e4698af32699.PNG)

**Comment by MarcMil** [comment]
As corresponded via mail, this is an apktoolbug, which is yet to be fixed by their team.

**Comment by MarcMil** [comment]
Finally, this bug has been fixed in apktool.
I have downloaded the newest nightly build; their fix works for me.

**Comment by MarcMil** [comment]
Closed due to inactivity; as said, the fix should be working.
If not, please reopen the bug.
