### ISSUE TITLE
Manually changed parameter becomes null if this parameter is given to a function

### ISSUE THREAD

**Issue by mutedmeta** [secure-software-engineering/CodeInspect#161]
Hello, 

I am experiencing problems when using the changing variable content feature while in debug mode. This happens in the following snippet of an antivirus app for android (com.zrgiu.antivirus)

```
$param2 = virtualinvoke $ScanFunc.<com.netqin.antivirus.scan.ScanFunc: java.lang.String avEngineCheckFile(java.lang.String, java.lang.String, java.lang.String, int)>($param0, $param1, $param2, $b1);
label6:
//staticinvoke <com.netqin.antivirus.util.a: void d(java.lang.String, java.lang.String)>("bai", $param2);
$ScanController_VirusEngineCheckFile = specialinvoke this.<com.netqin.antivirus.scan.j: com.netqin.antivirus.scan.ScanController$VirusEngineCheckFile a(java.lang.String)>($param2);
```

I am now stepping through this code line by line. In the first line $param2 is set to:
```
{\n\t"ripper":0,\n\t"IsVirus":false,\n\t"KeyID":0,\n\t"WhiteList":0,\n\t"VirusName":null,\n\t"NickName":null,\n\t"VirusClass":null,\n\t"CertHash":"30E082B7B4AE9D3AFF5E021833936C38C67799B5",\n\t"err":0\n}
```
I now make changes in this JSON-data in the variables window in the debug mode in Codeinspect. Then this changed data will be given to the function a in label6. 

This function looks like this:
```
private com.netqin.antivirus.scan.ScanController$VirusEngineCheckFile a(java.lang.String $param0)
  {
    org.json.JSONException $JSONException;
    org.json.JSONObject $JSONObject;
    com.netqin.antivirus.scan.ScanController$VirusEngineCheckFile $ScanController_VirusEngineCheckFile;
    int $int;
```

$param0 is the String with the JSON-Object. If I change the value like I described $param0 is going to be null in the Variables Window and the app will crash, no matter how I changed the variable. If I do not change anything the JSON-String is passed correctly. I updated to the newest version `CodeInspect v. 1426, built on 06/09/15 18:09`, and this behaviour stays the same. 

How can I resolve this issue?

**Comment by MarcMil** [comment]
Sounds strange. Works for me. I was able to change the value successfully. What Emulator do you use? I used Samsung Galaxy S3 - 4.2.2 - API 17 on Genymotion.

**Comment by mutedmeta** [comment]
Ok, I also tried it with Genymotion (after installing ARM Translation) and it works even with the version I've got. I used the Android SDK Emulator with an Android 5.1.1 armeabi-v7a Image. So it seems to be an emulator specific problem. Maybe my Android Sdk emulator is too old.
