### ISSUE TITLE
Better error message for ABI mismatch

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#174]
If an Android app uses native code which is only available for ARM and the user tries to run or debug it on an x86 emulator, CodeInspect displays a message "INSTALL_FAILED_NO_MATCHING_ABIS". It would be better to have a more descriptive message that tells the user that the app is not supported on his selected device and that lists the target platforms on which it would run (i.e., for which there are native libraries included).

**Comment by MarcMil** [comment]
Implemented
