### ISSUE TITLE
Soot instance not found after importing an APK

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#175]
Directly after importing a second APK into a workspace that already contained one APK, the attached error message was shown. The import completed without errors, the imported APK also looked complete.
![error](https://cloud.githubusercontent.com/assets/2691304/9819398/0da49dd6-58ae-11e5-9226-f6dc08f18819.png)

**Comment by MarcMil** [comment]
Is this still an issue? Works for me.

**Comment by StevenArzt** [comment]
Seems to work now.
