### ISSUE TITLE
URLs in Welcome page point to domain that returns 403: Forbidden

### ISSUE THREAD

**Issue by csdodd** [secure-software-engineering/CodeInspect#177]
The following URLs are all present on the Welcome page and all return HTTP 403: Forbidden.

- Visit the CodeInspect website (https://codeinspect.sit.fraunhofer.de/drupal7/?q=faq)
- Check out videos for Getting Started (https://codeinspect.sit.fraunhofer.de/drupal7/?q=videos)
- Stuck? Maybe there is already a solution in our FAQ (https://codeinspect.sit.fraunhofer.de/drupal7/?q=faq)

That the first URL also points to the FAQ may or may not be an issue.

**Comment by StevenArzt** [comment]
The CodeInspect web page has not officially been released. Accesses from outside our own network will therefore be denied for the time being. We are currently planning to go live at the beginning of October, together with the first official CodeInspect 1.0 production release.
