### ISSUE TITLE
Stuck on "Launching : Launching delegate" when attempting to debug

### ISSUE THREAD

**Issue by csdodd** [secure-software-engineering/CodeInspect#178]
Steps to reproduce

1) Import an APK
2) Click 'Debug'

What should happen:
CodeInspect should launch in debug mode and allow debugging.

What does happen:
CodeInspect never launches in debug mode; it stops indefinitely at 57% and the message "Launching : Launching delegate"

Additional Information:
I have tried this on a physical device and emulator; both with the same result. I've restarted CodeInspect and my machine. I've ensured that the start activity is set to automatic and confirmed that the activity it starts is the one defined as `Launcher` in the Manifest. I am running v 1452 of CodeInspect on v 10.10.5 of OS X.

**Comment by srasthofer** [comment]
Thanks for reporting. Could you check whether the view for device-picking is behind (hidden) the CodeInspect view.

**Comment by StevenArzt** [comment]
Have you checked whether the window for selecting the target (start an emulator or select a running one) has been launched in the background? It sometimes happens that this window shows up behind the CodeInspect main window. The tool then appears to be stuck, but is in fact waiting for user input.

**Comment by csdodd** [comment]
This happens after I have chosen the device. Once it hangs the device is stuck and renders:

    Waiting For Debugger

    Application ... is waiting for the debugger to attach.

**Comment by StevenArzt** [comment]
Is this an emulator or a real device? Which Android version do you use?

**Comment by csdodd** [comment]
That was on a real device running the latest Android 6.0 build (API v23), I did try on an emulator but it wasn't successful but that may have been because the emulator wasn't running when I tried deploying to it. I can try an emulator again.

**Comment by StevenArzt** [comment]
I have used CodeInspect on real devices running API 22 and on an emulator running 23 which worked. I don't have a real device running 23 yet, so I cannot exactly reproduce it using your environment. In the worst case, try restarting the adb deamon (or rebooting the machine) in case Google's adb got stuck.

**Comment by csdodd** [comment]
I tried again on a device running Android v4.4.4 and it worked; perhaps the problem only occurs on hardware running API 23.

**Comment by StevenArzt** [comment]
We'll double-check this once we have a real device running API 23.

**Comment by StevenArzt** [comment]
It takes a while before the Device Chooser window appears, but it works even with a real device running Android 23. I guess the problem has been fixed in the meantime. If you still have issues, please report them here.
