### ISSUE TITLE
Layout editor doesn't work

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#180]
If I open a layout XML file in CodeInspect, the tool only reports "Loading editor", but never actually displays the layout contents in the UI. We have recordings of that UI from one of Siegfried's older tasks. I'm not sure whether it used to work and broke or whether that's an issue with Windows, as Siegfried's presentation was done on Mac.

**Comment by csdodd** [comment]
I can confirm I am seeing the same "Loading Editor" hang on Mac.

**Comment by MarcMil** [comment]
Issues have been fixed on this side. Please retry; it should work now.

**Comment by StevenArzt** [comment]
Works. Thanks a lot, @MarcMil
