### ISSUE TITLE
Launchable activity selection gets erased on project change

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#190]
When I create a new launch configuration for debugging an Android app, the "launch activity" is initially set to "Automatic detection". If I, however, change the project, the launch activity is changed to empty which is not useful. It would be better to keep "Automatic detection". Clearing the field on project change only makes sense if a particular concrete activity was set before. In that case, it should still be cleared.

**Comment by MarcMil** [comment]
Fixed
