### ISSUE TITLE
Add export option for APKs

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#192]
Add a feature to export a (potentially modified) APK from CodeInspect. This function should allow the user to specify a specific keystore and password (or use the built-in one) and to ZipAlign. The normal CodeInspect config entries for keystore and zipalign should be used as default, but the user should be able to specify different settings in the export wizard. Additionally, the user should be able to disable debugging for the exported APK.

**Comment by MarcMil** [comment]
Implemented

**Comment by StevenArzt** [comment]
Great work, the export wizard contains all the relevant features and is quite user-friendly with lots of error checking and hints for the user. Thanks @MarcMil
