### ISSUE TITLE
Icon in Mac Dock gets replaces after deploying code

### ISSUE THREAD

**Issue by csdodd** [secure-software-engineering/CodeInspect#194]
The icon in the dock loads correctly until I deploy code at which point it gets replaced:
![image](https://cloud.githubusercontent.com/assets/4302925/10481599/daefb6c2-7271-11e5-9ea0-2595579768ea.png)

More Info: This is on El Capitan but it happened before the upgrade; running v. 1513

**Comment by MarcMil** [comment]
Fixed
