### ISSUE TITLE
Android target version lost after CodeInspect update

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#195]
After updating CodeInspect, the target version for the existing projects are no longer set. The Android console shows the following message and there is a red cross at the project in the project explorer:

```
[2015-10-20 04:23:35 - KoreaBankingTrojan] Project has no target set. Edit the project properties to set one.
```

In the properties dialog, the version is set to automatic detection. Removing the project from the workspace and importing the existing project (not the APK) again does not solve the issue. Only re-importing the APK solved the problem, but I lost my breakpoints and code changes using this method.

**Comment by MarcMil** [comment]
Fixed
