### ISSUE TITLE
Bug of ImportReport.html

### ISSUE THREAD

**Issue by somebody365** [secure-software-engineering/CodeInspect#198]
![image](https://cloud.githubusercontent.com/assets/5002059/12252847/e29c8d4c-b915-11e5-9539-38cc9b50a812.png)

**Comment by MarcMil** [comment]
Thanks for submitting a bug.

What is the specific problem about that file?
Is the date format wrong?
The date is returned DateFormat.getInstance().format(new Date()))
In this case: What is your system locale? What do you expect instead?

**Comment by somebody365** [comment]
It's this,
    Import report
        Created on 16-1-12 涓婂崍10:29
     Import warnings:
        No errors during import. 
"涓婂崍" should be "am", I don't know why.
My system is Windows (Chinese Simplified).



wykcomputer@163.com
 
From: Marc Miltenberger
Date: 2016-01-12 15:21
To: secure-software-engineering/CodeInspect
CC: somebody365
Subject: Re: [CodeInspect] Bug of ImportReport.html (#198)
Thanks for submitting a bug.
What is the specific problem about that file?
Is the date format wrong?
The date is returned DateFormat.getInstance().format(new Date()))
In this case: What is your system locale? What do you expect instead?

**Comment by MarcMil** [comment]
OK, for now we are using a generic date/time format for everyone:
dd/MM/yy HH:mm
12/01/16 11:35

Also has the advantage that it is consistent across different platforms and locals.
