### ISSUE TITLE
Issue deploying to tablet running Android 6.0

### ISSUE THREAD

**Issue by csdodd** [secure-software-engineering/CodeInspect#199]
I have a Nexus 9 tablet running Android v6.0; when attempting to launch a debug build on the device I get the following error.
<img width="598" alt="screen shot 2016-02-06 at 22 14 07" src="https://cloud.githubusercontent.com/assets/4302925/12869410/f9432f16-cd1e-11e5-8461-74af8e70ce5e.png">

On the device it is stuck waiting for the debugger to attach. Happens 100% of the time, can not reproduce on a device running Android v4.4.4

**Comment by csdodd** [comment]
More Info, Android Studio isn't running. Flushing adb via `adb kill-server` and `adb start-server` does not help.

**Comment by StevenArzt** [comment]
Does this happen with every app or only with a single one? Does this happen only on tablets or also on normal phones? I have tested the build from 02/02/16 with a phone running Android 6.0.1 and didn't receive the error message. It would be great to have more information about your exact setup so that we can reproduce the issue.

**Comment by csdodd** [comment]
The same code that wouldn't deploy to the tablet did deploy correctly to an Android phone running 6.0.1. I don't have the tablet with me right now but I will check if it is just one app or all apps.

I'm running:
El Capitan 10.11.3.
CodeInspect v. 1998, built on 05/02/16 15:02
java.runtime.version=1.8.0_66-b17

**Comment by StevenArzt** [comment]
I just tried to deploy an app to an emulator running Nexus 9 with Android 6.0 x86 and it worked. I'm really curious to hear whether the issue arises only with that one app or with all apps. One additional question: Is your tablet based on x86 or on ARM?

**Comment by StevenArzt** [comment]
I have also checked using our tablets here. On a Nexus 7 running Android 6.0 and a Samsung Galaxy Tab 3 running Android 4.4.2, I could debug my test app just fine.

**Comment by csdodd** [comment]
Apologies for the delay in updating this issue. All apps failed to deploy to the Nexus 9.

It's an ARM device, but it is 64 bit.

**Comment by MarcMil** [comment]
We do not have a physical ARM device yet, but we have changed some parts on the debugging site, which might have fixed your issue.
Could you please retry with the current version? You would have to clean the project via Project/Clean.

**Comment by csdodd** [comment]
Have just tried with CodeInspect v. 2048 (built on 06/03/16) and Nexus 9 running Android N (NPC56P) and it deployed successfully.

I will close this issue.
