### ISSUE TITLE
built 0418 runs too slow

### ISSUE THREAD

**Issue by colordancer** [secure-software-engineering/CodeInspect#206]
CodeInpsect worked well for previous nightly built. But after I upgraded it to built on April 18th, CI ran too much slower. Even opening the eclipse preferences dialog took one minute or so. From the command line, I saw there was a pulse connection. So I guessed I had a bad pulse connection to the serve from China so that the interactions were stuck. 

My environment is Ubuntu 16.04, with 8G memory.

```
colordancer@colordancer-ubuntu:~/android/codeInspect$ ./CodeInspect -clean
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Running in vm :
Oracle Corporation
http://java.oracle.com/
1.8.0_66
Oracle Corporation
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
CodeInspect version: v. 0.2 Nightly (2107/18/04/16 08:04)
Pulsing
Connecting in order to pulse...
Browser error: No more handles [Browser style SWT.MOZILLA and Java system property org.eclipse.swt.browser.DefaultType=mozilla are not supported with GTK 3 as XULRunner is not ported for GTK 3 yet]
```

**Comment by MarcMil** [comment]
Hi colordancer,
try using
> env SWT_GTK3=0 UBUNTU_MENUPROXY=0 ./CodeInspect

Canonical seems to have messed up something with Xenial; eclipse is suffering this problem too. I hope, they fix it soon.

Marc

**Comment by colordancer** [comment]
@MarcMil Thanks. But unluckily it doesn't work with the new env. Is there any other measures I could try? If not, it seems I'd better downgrade to Ubuntu 15.

**Comment by MarcMil** [comment]
That's odd.
I am using this on my Ubuntu 16.04 and it works flawlessly (using this exact command).
env does only set the environment for the command which is after the environment variables.

If it still looks like this, something went wrong when applying the environment variables:
![Slow env CI Version Image](http://s32.postimg.org/pc19jv611/Slow.png)
In this case, you could try running
`
export SWT_GTK3=0
export UBUNTU_MENUPROXY=0
./CodeInspect
`

If it looks like the following, it should work fine.
![Fast env CI Version Image](http://s32.postimg.org/41hy478zp/Fast.png)


I am downloading a fresh iso of Ubuntu 16.04 and test it.

**Comment by colordancer** [comment]
@MarcMil cheers. this time it works. I used the env in a wrong way previously. Thank you.

**Comment by MarcMil** [comment]
Well, that's nice to hear ;)
