### ISSUE TITLE
Debugging Android apps from source does not work

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#31]
One can import an Android app source code project into CodeInspect and everything looks normal, but when one attempts to launch the app, CodeInspect complains that the APK file was missing. Since the .class files (on which the ADT would then run the dx tool) are created by Eclipse anyway, would it be possible to generate the APK? Instead of applying Soot on Jimple files to produce the APK, one would just have to apply it on the Java class files (not on the Java sources files, that frontend is a bit shaky).

**Comment by MarcMil** [comment]
Since we have added the ADT plugin, you can now use the original ADT plugin to debug the App.
