### ISSUE TITLE
FlowDroid Visualization: Improve Calltrace View

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#32]
The calltrace flow in the FlowDroid visualization plugin is a simple textual list at the moment. There should be a more advanced list that is easier to read given that we don't only have the source code line, but also the containing method. An entry that has two lines (one for the containing method and one for the statement), potentially with different colors or other visual aid, would be much easier to read.

**Comment by alexanderj1988** [comment]
View improved by showing information in a table
