### ISSUE TITLE
Code Highlighting in Jimple

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#34]
If the cursor is placed over a an element such as variable occurrence, a function call, etc., the normal Eclipse Java editor highlights all other occurrences of that code items (i.e., references to the same variable, calls to the same function, etc.) in gray. This is very convenient when trying to understand code and it would be great to have such a feature in the Jimple editor as well.

**Comment by StevenArzt** [comment]
@MarcMil  What's the status of this issue?

**Comment by MarcMil** [comment]
Implemented
