### ISSUE TITLE
Flow Visualizer: Put numbers on data flow arrows

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#38]
In the flow visualizer, there should be an option (toggle on/off) to display ordering numbers next to the arrows. This should independently be possible for the arrows on the code and those in the UML-style diagram. The ordering shall show which data flow edge occurs first in the program, which one second, etc.

**Comment by alexanderj1988** [comment]
fixed, but is not represented correcty because of zest1. This will change after an update to zest2, but api is not marked as stable yet
