### ISSUE TITLE
No direct jump to class from strings

### ISSUE THREAD

**Issue by srasthofer** [secure-software-engineering/CodeInspect#43]
If there is a constant string in a class like:
<android.content.ComponentName: void <init>(java.lang.String,java.lang.String)>($r3, "com.a.b");

it does not jump to "com.a.b".
But if there is a
"com/a/b" in an intent, it works!

**Comment by MarcMil** [comment]
Would not count it as a bug; it is rather a feature.
It is a string, not a Jimple class constant (class "bla/bla/bla"), therefore there is no hyperlink ;)
However, good point, adding hyperlinks to constant strings looking like class constants would not be a bad idea.

**Comment by srasthofer** [comment]
yep you are right. just took the bug label to get more attraction :-)

**Comment by MarcMil** [comment]
Look forward to the next nightly build in around one hour ;)
