### ISSUE TITLE
Handy wird im Dialog "Import APK from Phone" doppelt angezeigt

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#46]
Es kann passieren, dass ein und dasselbe Gerät doppelt in der Liste der verfügbaren Geräte aufgeführt wird. Das sollte man besser filtern, weil es verwirren kann.

**Comment by MarcMil** [comment]
Check wurde hinzugefügt; ich konnte das doppelte Hinzufügen nicht reproduzieren, sollte aber nun nicht mehr möglich sein.
