### ISSUE TITLE
Einträge im Dialog "Import APK from Phone" sortierbar machen

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#47]
Es wäre gut, wenn man die einzelnen APKs, die man vom Handy herunterladen kann, durch einen Klick auf die Titelzeile der Tabelle nach dem entsprechenden Datenfeld (Packagename, Dateiname, usw.) sortieren könnte.

**Comment by MarcMil** [comment]
Ist drin (im nächsten Nightly build).
