### ISSUE TITLE
Debugger disconnects by incoming calls 

### ISSUE THREAD

**Issue by srasthofer** [secure-software-engineering/CodeInspect#49]
I have an application with a broadcast receiver waiting for incoming calls. 
Initializing a call via 
telnet localhost 5554
gsm call 1234

Disconnects the debugger and there is no exception in -consolelog. App will be provided by request.
Thanks!

**Comment by MarcMil** [comment]
Have a look at 
https://developer.android.com/reference/android/content/BroadcastReceiver.html#onReceive(android.content.Context, android.content.Intent)
When it runs on the main thread you should never perform long-running operations in it (there is a timeout of 10 seconds that the system allows before considering the receiver to be blocked and a candidate to be killed).

So you should not debug longer than ten seconds. You could try to create a new thread instead and debug it. Sadly, this is currently the only option I see besides patching the Android code.

**Comment by srasthofer** [comment]
No, it is in a separate threat and it is quits immediately, so not even a second...

**Comment by MarcMil** [comment]
Seems to be related to the emulator (http://stackoverflow.com/questions/19644465/device-disconnects-after-a-call)

**Comment by srasthofer** [comment]
Yes, used Intel X86 on mac. Works with standard ARM emulator
