### ISSUE TITLE
Display original certificate for application

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#61]
It would be great to have some UI for displaying the original certificate (issuer name, etc.) of the APK. It would also be great to be able to export that certificate into a file.

**Comment by MarcMil** [comment]
How about a property page, which gets displayed if you use the context menu/Properties on the respective apk file?

**Comment by StevenArzt** [comment]
Sounds good to me.

**Comment by MarcMil** [comment]
Has been implemented. It has not a nice UI yet, but seeing information about then and exporting the certificate in different formats is already possible.
