### ISSUE TITLE
CodeInspect: Bundling JVM (esp. Mac)

### ISSUE THREAD

**Issue by MarcMil** [secure-software-engineering/CodeInspect#79]
There is still some work to do on this.

**Comment by StevenArzt** [comment]
@MarcMil What's the status on this?

**Comment by MarcMil** [comment]
https://github.com/secure-software-engineering/CodeInspect/issues/78
The problem is, adb requires a version of java version installed. The DDMS plugin takes care of starting the adb server if it is has not been started yet. However, we have our own version of the DDMS plugin anyway, so it's possible to patch it.
We must somehow make sure that adb uses the bundled jre which is not known to the OS.

**Comment by MarcMil** [comment]
Bundled JRE is used
