### ISSUE TITLE
Install Failed Exception

### ISSUE THREAD

**Issue by srasthofer** [secure-software-engineering/CodeInspect#80]
@ofercas reported an install failed exception in #78. I closed #78 and opened a new issue:
![bildschirmfoto 2015-03-09 um 08 52 57](https://cloud.githubusercontent.com/assets/3647928/6551515/0f55c116-c63a-11e4-9c0e-dfa86894820f.png)

@ofercas Is it possible that you send as the apk or a minimal version of the apk reproducing the error? You can send it to me via email or upload it to a server.

**Comment by ofercas** [comment]
@srasthofer Sure, I sent you by email.

**Comment by srasthofer** [comment]
Unfortunately, we could not reproduce your issue. On our machines (MacOS + Linux) we are able to debug the sample you sent.
What are your settings:
- emulator (x86 or ARM) + emulator version
- android.jar version

Thanks!

**Comment by ofercas** [comment]
I'm using the latest update of emulator & android from sdk.
My AVD setup is using ARM, Nexus One, Android 4.1.2.

Imported/Output.apk available here:
https://www.wetransfer.com/downloads/c69213c744faf1f9d7424b2a3857ed8920150310073616/198e5a55fb8b82e794ca0d1a5b2a164520150310073616/94ae07

**Comment by MarcMil** [comment]
Thanks for your help.
This seems to be actually a bug within Dexlib2, which we use to write the apk files. I have forwarded the issue to the developer.
I will update this issue as soon I know more.

**Comment by MarcMil** [comment]
This bug should now be fixed. Please download the new version and try again.

The relevant corresponding smali bug is
https://code.google.com/p/smali/issues/detail?id=236#makechanges
