### ISSUE TITLE
Debug not responding

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/CodeInspect#85]
As in https://github.com/secure-software-engineering/CodeInspect/issues/82, the output.apk has successfully be compiled, however launching debug seems stuck infinitely.

vmargs:
 -vmargs
-Xms4g
-Xmx20g
-XX:PermSize=1024m
-XX:MaxPermSize=2048m

![screenshot from 2015-03-12 11 08 47](https://cloud.githubusercontent.com/assets/2270027/6611528/3087cf30-c8a8-11e4-8395-e2ec6df2205d.png)

**Comment by MarcMil** [comment]
adb does sometimes not work faithfully. However, CodeInspect now retries multiple times. Be also sure that the "Select device window" is not somewhere in the background.

**Comment by flankerhqd** [comment]
Seems is the latter issue, closing it now.
