### ISSUE TITLE
license window cloning

### ISSUE THREAD

**Issue by markuzSchmidt** [secure-software-engineering/CodeInspect#86]
The "Enter license code" dialog which appears on first start duplicates when pressing the "Refresh"-button or "Add new license"->*leaving everything empty*->"Ok" __while no license is registered__. It's possible to do this in the new dialog as well and therefore create 20 new dialogs by pressing "Refresh" 20 times.
As soon as a license code is added, this issue no longer occurs.

Im using the windows_64 version.

**Comment by MarcMil** [comment]
This one is fixed now
