### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by madnote** [secure-software-engineering/CodeInspect#95]
It would be great if you could add http proxy support for the license verification. 

I'm using the x64 windows version of CodeInspect and the system proxy is set. But as you can see, it is not able to connect to the license server:

![screenshot](https://cloud.githubusercontent.com/assets/7040681/6731473/681506aa-ce45-11e4-8df0-de55427ea0ac.jpg)

**Comment by MarcMil** [comment]
The most recent version of CodeInspect should now respect Eclipse's proxy settings. You can also find the "Connection settings" button at the bottom of the license code window, where you can set these settings. That window should appear after clicking OK on the license error dialog.
If it still does not work with the new version, please tell me
the type of proxy (https, http or socks?)
and whether some sort of authentication is used (we only support Basic authentication at the moment).
