### ISSUE TITLE
CodeInspect doesn't produce output.apk on OSX

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/CodeInspect#98]
Clicking "build project" and/or "run" and/or "debug" shows the following error:

![image](https://cloud.githubusercontent.com/assets/2270027/6748581/31cc069c-cf22-11e4-93e6-08a1dc51a883.png)

Seems one cannot get output.apk. Tried different apks but still cannot get output.apk for debug and run.

**Comment by flankerhqd** [comment]
Same apk on linux edition codeinspect runs well.

**Comment by MarcMil** [comment]
That's strange; there shouldn't be a real difference between the different variants.

Maybe could you start CodeInspect via the terminal from the CodeInspect path with
./CodeInspect.app/Contents/MacOS/CodeInspect -consolelog

and copy the log into this issue?

**Comment by MarcMil** [comment]
Finally, we could reproduce this bug on a OS X system. This should be fixed now, if not, please reopen the issue.
